"""
podcasts.py — Curated daily podcast episode recommendation for AI News Digest.

All entries are real, specific, widely-referenced episodes.
One is selected per day using a date-based rotation (same pick for the whole day).
"""

from datetime import date

# ---------------------------------------------------------------------------
# Curated list of specific, famous podcast episodes
# ---------------------------------------------------------------------------
EPISODES: list[dict] = [
    {
        "show": "Lex Fridman Podcast",
        "episode": "Sam Altman: OpenAI CEO on GPT-4, ChatGPT, and the Future of AI",
        "episode_id": "#367",
        "guest": "Sam Altman",
        "category": "AI",
        "duration": "~2h 25min",
        "why": "Sam Altman explains how OpenAI decided to release ChatGPT, why he thinks AGI is closer than most people believe, and what keeps him up at night. One of the most candid AI CEO interviews ever recorded.",
        "spotify_search": "Lex Fridman Sam Altman GPT-4 367",
    },
    {
        "show": "Lex Fridman Podcast",
        "episode": "Geoffrey Hinton: The Godfather of Deep Learning on AI Risk",
        "episode_id": "#419",
        "guest": "Geoffrey Hinton",
        "category": "AI",
        "duration": "~2h 36min",
        "why": "The man who invented the foundations of modern AI explains why he left Google, why he's now scared of what he helped create, and what he thinks we should do about it. A must-listen for anyone following AI.",
        "spotify_search": "Lex Fridman Geoffrey Hinton 419",
    },
    {
        "show": "Lex Fridman Podcast",
        "episode": "Andrej Karpathy: Tesla AI, Self-Driving, and the Future of AI",
        "episode_id": "#333",
        "guest": "Andrej Karpathy",
        "category": "AI",
        "duration": "~3h 15min",
        "why": "Tesla's former AI director (now back at OpenAI) breaks down how self-driving AI actually works, why it's harder than people think, and what the path to general intelligence looks like from the inside.",
        "spotify_search": "Lex Fridman Andrej Karpathy 333",
    },
    {
        "show": "Lex Fridman Podcast",
        "episode": "Yann LeCun: Dark Matter of Intelligence and Self-Supervised Learning",
        "episode_id": "#258",
        "guest": "Yann LeCun",
        "category": "AI",
        "duration": "~2h 45min",
        "why": "Meta's Chief AI Scientist debates whether large language models can ever be truly intelligent and why he thinks the AI field is taking the wrong path. Provocative and fascinating.",
        "spotify_search": "Lex Fridman Yann LeCun 258",
    },
    {
        "show": "Lex Fridman Podcast",
        "episode": "Mark Zuckerberg: Future of AI at Meta, Llama, and Open Source",
        "episode_id": "#399",
        "guest": "Mark Zuckerberg",
        "category": "AI & Business",
        "duration": "~2h 25min",
        "why": "Zuckerberg explains why Meta decided to open-source its AI models (a move most thought was insane), how he thinks about competition with OpenAI, and where he sees AI going in the next decade.",
        "spotify_search": "Lex Fridman Mark Zuckerberg 399",
    },
    {
        "show": "Lex Fridman Podcast",
        "episode": "Elon Musk: War, AI, Aliens, Politics, Physics, Video Games",
        "episode_id": "#400",
        "guest": "Elon Musk",
        "category": "Tech & AI",
        "duration": "~7h 40min",
        "why": "The longest podcast episode Lex ever recorded — Musk covers everything from his fears about AI to Twitter/X to Mars colonization. Even if you only listen to an hour of it, it's unlike any other interview.",
        "spotify_search": "Lex Fridman Elon Musk 400",
    },
    {
        "show": "Hard Fork (New York Times)",
        "episode": "The Sam Altman Firing",
        "episode_id": "Nov 2023",
        "guest": "Kevin Roose & Casey Newton",
        "category": "AI News",
        "duration": "~55min",
        "why": "Recorded the weekend Sam Altman was suddenly fired from OpenAI — and then rehired five days later. Kevin and Casey were breaking the story in real time. One of the most gripping tech news episodes ever made.",
        "spotify_search": "Hard Fork Sam Altman Firing New York Times",
    },
    {
        "show": "Hard Fork (New York Times)",
        "episode": "ChatGPT Changed Everything",
        "episode_id": "Dec 2022",
        "guest": "Kevin Roose & Casey Newton",
        "category": "AI",
        "duration": "~48min",
        "why": "Recorded just after ChatGPT launched to the public — Kevin and Casey try to make sense of what just happened and why it feels different from every other AI announcement. Fascinating to hear in retrospect.",
        "spotify_search": "Hard Fork ChatGPT Changed Everything 2022",
    },
    {
        "show": "Acquired",
        "episode": "NVIDIA: The Most Important Company in the World",
        "episode_id": "Season 13",
        "guest": "Ben Gilbert & David Rosenthal",
        "category": "Business History",
        "duration": "~8h 45min",
        "why": "The definitive story of how Jensen Huang turned a gaming chip company into the infrastructure backbone of the AI revolution. Understanding NVIDIA means understanding why the AI boom happened when it did.",
        "spotify_search": "Acquired NVIDIA Jensen Huang",
    },
    {
        "show": "Acquired",
        "episode": "Apple: The Greatest Business Ever",
        "episode_id": "Season 12",
        "guest": "Ben Gilbert & David Rosenthal",
        "category": "Business History",
        "duration": "~9h 12min",
        "why": "A full sweep of Apple's history — from near-bankruptcy in 1997 to becoming the first $3 trillion company. If you've ever wondered how Apple really works as a business, this is the answer.",
        "spotify_search": "Acquired Apple Greatest Business",
    },
    {
        "show": "Acquired",
        "episode": "Berkshire Hathaway",
        "episode_id": "Season 11",
        "guest": "Ben Gilbert & David Rosenthal",
        "category": "Investing & Business",
        "duration": "~8h 30min",
        "why": "The full story of how Warren Buffett turned a failing textile mill into the greatest investment vehicle in history. Packed with lessons on compounding, patience, and how the world's best investors actually think.",
        "spotify_search": "Acquired Berkshire Hathaway Buffett",
    },
    {
        "show": "Acquired",
        "episode": "Amazon",
        "episode_id": "Season 9",
        "guest": "Ben Gilbert & David Rosenthal",
        "category": "Business History",
        "duration": "~6h 58min",
        "why": "How Jeff Bezos built Amazon from an online bookstore to the everything store to AWS — the cloud computing empire that now powers most of the internet, including a lot of AI infrastructure.",
        "spotify_search": "Acquired Amazon Jeff Bezos",
    },
    {
        "show": "How I Built This (NPR)",
        "episode": "Airbnb: Brian Chesky",
        "episode_id": "2020",
        "guest": "Brian Chesky",
        "category": "Entrepreneurship",
        "duration": "~55min",
        "why": "Chesky tells the real story — selling cereal boxes called 'Obama O's' to survive, getting rejected by 7 of 8 investors, and how they nearly died during COVID before becoming one of the most valuable companies on earth.",
        "spotify_search": "How I Built This Airbnb Brian Chesky NPR",
    },
    {
        "show": "How I Built This (NPR)",
        "episode": "Spanx: Sara Blakely",
        "episode_id": "2019",
        "guest": "Sara Blakely",
        "category": "Entrepreneurship",
        "duration": "~48min",
        "why": "Sara Blakely started Spanx with $5,000, no business experience, and a fax machine. She kept the idea secret for a year and became the world's youngest self-made female billionaire. A genuinely remarkable story.",
        "spotify_search": "How I Built This Spanx Sara Blakely NPR",
    },
    {
        "show": "How I Built This (NPR)",
        "episode": "Duolingo: Luis von Ahn",
        "episode_id": "2021",
        "guest": "Luis von Ahn",
        "category": "Entrepreneurship & EdTech",
        "duration": "~52min",
        "why": "The inventor of CAPTCHA built Duolingo to give everyone in the world free language education — and figured out how to make it feel like a game. One of the most thoughtful tech-for-good stories out there.",
        "spotify_search": "How I Built This Duolingo Luis von Ahn NPR",
    },
    {
        "show": "All-In Podcast",
        "episode": "AI's Inflection Point: What GPT-4 Changes",
        "episode_id": "E119 (March 2023)",
        "guest": "Chamath, Jason, Sacks & Friedberg",
        "category": "AI & Venture Capital",
        "duration": "~1h 20min",
        "why": "Recorded right after GPT-4 launched — four top investors debate what it actually means for the economy, jobs, and their own portfolios. Unfiltered and full of strong opinions.",
        "spotify_search": "All-In Podcast E119 GPT-4 AI Inflection",
    },
    {
        "show": "All-In Podcast",
        "episode": "State of AI: Who's Winning the AI Race?",
        "episode_id": "E154 (2024)",
        "guest": "Chamath, Jason, Sacks & Friedberg",
        "category": "AI & Business",
        "duration": "~1h 35min",
        "why": "A frank conversation about where OpenAI, Google, Meta, and Anthropic actually stand in the AI race — including what each is getting right and wrong. Good for understanding the competitive landscape.",
        "spotify_search": "All-In Podcast State of AI 2024 E154",
    },
    {
        "show": "Masters of Scale",
        "episode": "Reed Hastings: The Netflix Culture That Shocked Silicon Valley",
        "episode_id": "Season 1",
        "guest": "Reed Hastings",
        "category": "Business Leadership",
        "duration": "~35min",
        "why": "Netflix's founder explains the 'no rules rules' management philosophy — no vacation policy, no approval processes, radical candor — and why he thinks most companies are run entirely wrong.",
        "spotify_search": "Masters of Scale Reed Hastings Netflix Culture",
    },
    {
        "show": "Masters of Scale",
        "episode": "Brian Chesky: The Airbnb Bounce Back",
        "episode_id": "2020",
        "guest": "Brian Chesky",
        "category": "Business & Crisis Management",
        "duration": "~40min",
        "why": "Chesky describes laying off 25% of Airbnb's staff during COVID on a Zoom call — how he did it, what he said, and why he personally wrote to every single employee. A masterclass in leading through crisis.",
        "spotify_search": "Masters of Scale Brian Chesky Airbnb Bounce Back",
    },
    {
        "show": "The Tim Ferriss Show",
        "episode": "Naval Ravikant: The Angel Philosopher",
        "episode_id": "#97",
        "guest": "Naval Ravikant",
        "category": "Philosophy & Wealth",
        "duration": "~2h 5min",
        "why": "Naval breaks down his philosophy on wealth, happiness, and leverage in a way that changes how you think about work. One of the most shared podcast episodes in the history of the medium — for good reason.",
        "spotify_search": "Tim Ferriss Naval Ravikant Angel Philosopher 97",
    },
    {
        "show": "The Tim Ferriss Show",
        "episode": "Arnold Schwarzenegger: Lessons From a Hall of Fame Career",
        "episode_id": "#444",
        "guest": "Arnold Schwarzenegger",
        "category": "Motivation & Leadership",
        "duration": "~1h 50min",
        "why": "Arnold talks about immigrant mindset, how he prepared obsessively for every role and competition, and the psychological tactics he used to dominate bodybuilding. Surprisingly practical and motivating.",
        "spotify_search": "Tim Ferriss Arnold Schwarzenegger 444",
    },
    {
        "show": "The Tim Ferriss Show",
        "episode": "Peter Thiel: The Science of Becoming a Billionaire",
        "episode_id": "#165",
        "guest": "Peter Thiel",
        "category": "Business & Investing",
        "duration": "~1h 20min",
        "why": "The PayPal co-founder and investor behind Facebook explains his controversial framework for building companies, why competition is for losers, and what most startup advice gets completely wrong.",
        "spotify_search": "Tim Ferriss Peter Thiel 165",
    },
    {
        "show": "Huberman Lab",
        "episode": "How to Increase Motivation and Drive",
        "episode_id": "Episode 39",
        "guest": "Andrew Huberman",
        "category": "Neuroscience & Productivity",
        "duration": "~2h 18min",
        "why": "Huberman explains the dopamine system in plain English — why procrastination happens, how to reset your motivation after burnout, and the specific daily behaviors that keep high performers running consistently.",
        "spotify_search": "Huberman Lab Motivation Drive Dopamine Episode 39",
    },
    {
        "show": "Huberman Lab",
        "episode": "Master Your Sleep and Be More Alert When Awake",
        "episode_id": "Episode 2",
        "guest": "Andrew Huberman",
        "category": "Health & Performance",
        "duration": "~1h 54min",
        "why": "The single most practical episode on sleep science — morning light, temperature, timing — with specific, free actions you can take today. Downloaded over 100 million times for a reason.",
        "spotify_search": "Huberman Lab Master Sleep Alert Episode 2",
    },
    {
        "show": "Pivot (Vox)",
        "episode": "The OpenAI Board Drama, Explained",
        "episode_id": "Nov 2023",
        "guest": "Kara Swisher & Scott Galloway",
        "category": "AI & Business",
        "duration": "~1h 5min",
        "why": "Recorded the week Sam Altman was fired and rehired — Kara had sources inside OpenAI and was breaking information nobody else had. The most eventful week in AI history, explained by the best reporters covering it.",
        "spotify_search": "Pivot Kara Swisher OpenAI Board Drama November 2023",
    },
    {
        "show": "Pivot (Vox)",
        "episode": "Is Google Cooked?",
        "episode_id": "2024",
        "guest": "Kara Swisher & Scott Galloway",
        "category": "AI & Business",
        "duration": "~58min",
        "why": "After Google's disastrous Gemini image generation controversy and multiple AI stumbles, Kara and Scott debate whether Google has permanently lost its lead in AI — and what that means for everything built on top of it.",
        "spotify_search": "Pivot Kara Swisher Is Google Cooked 2024",
    },
    {
        "show": "My First Million",
        "episode": "The Sam Parr Portfolio: How I'd Invest $100K Today Using AI",
        "episode_id": "2024",
        "guest": "Sam Parr & Shaan Puri",
        "category": "Business Ideas & AI",
        "duration": "~1h 15min",
        "why": "Sam and Shaan brainstorm specific business ideas you can start today using AI tools — with real numbers, real markets, and the kinds of ideas that big companies are too slow to build. Practical and energizing.",
        "spotify_search": "My First Million Sam Parr AI Business Ideas 2024",
    },
    {
        "show": "My First Million",
        "episode": "How to Build a One-Person Business with AI",
        "episode_id": "2023",
        "guest": "Sam Parr & Shaan Puri",
        "category": "AI & Entrepreneurship",
        "duration": "~1h 10min",
        "why": "The hosts map out how a single person with AI tools can now do the work of a team of 10 — with specific examples of solo founders building multi-million dollar businesses. Eye-opening if you think big companies always win.",
        "spotify_search": "My First Million One Person Business AI 2023",
    },
    {
        "show": "20VC (The Twenty Minute VC)",
        "episode": "Sam Altman: The Full Picture on OpenAI's Mission, Money, and Future",
        "episode_id": "2023",
        "guest": "Sam Altman",
        "category": "AI & Venture Capital",
        "duration": "~1h 30min",
        "why": "Harry asks the uncomfortable questions — how much money OpenAI is losing, how they think about safety vs. speed, and what Altman personally believes about where all of this is headed. Very direct.",
        "spotify_search": "20VC Sam Altman OpenAI Mission 2023",
    },
    {
        "show": "20VC (The Twenty Minute VC)",
        "episode": "Jensen Huang: Building NVIDIA and the AI Supercycle",
        "episode_id": "2024",
        "guest": "Jensen Huang",
        "category": "AI & Business",
        "duration": "~1h 20min",
        "why": "Jensen Huang explains how NVIDIA survived near-bankruptcy, why he made the bet on GPUs for AI long before anyone thought it would pay off, and what he sees coming next that most people are still missing.",
        "spotify_search": "20VC Jensen Huang NVIDIA AI 2024",
    },
    {
        "show": "No Priors",
        "episode": "Anthropic CEO Dario Amodei on Claude, Safety, and Building AI Responsibly",
        "episode_id": "2023",
        "guest": "Dario Amodei",
        "category": "AI",
        "duration": "~55min",
        "why": "Anthropic's CEO explains why he left OpenAI to start a safety-focused competitor, how Claude is different from ChatGPT, and what 'responsible AI development' actually means in practice — not just as marketing.",
        "spotify_search": "No Priors Dario Amodei Anthropic Claude Safety",
    },
    {
        "show": "No Priors",
        "episode": "Mustafa Suleyman on Building DeepMind, Inflection, and Microsoft AI",
        "episode_id": "2024",
        "guest": "Mustafa Suleyman",
        "category": "AI",
        "duration": "~50min",
        "why": "One of the co-founders of DeepMind (Google's AI lab) explains what it was like building AI before it was cool, what he learned running Inflection, and why he joined Microsoft to lead their AI division.",
        "spotify_search": "No Priors Mustafa Suleyman DeepMind Microsoft AI",
    },
    {
        "show": "Latent Space",
        "episode": "The History of Open Source AI: Llama, Mistral, and the Open Model Wars",
        "episode_id": "2024",
        "guest": "Various AI researchers",
        "category": "AI Engineering",
        "duration": "~1h 30min",
        "why": "A detailed look at how Meta's Llama models leaked/launched, why Mistral emerged from Europe, and what open-source AI actually means for the future — told by the engineers in the middle of it.",
        "spotify_search": "Latent Space Llama Mistral Open Source AI Wars",
    },
    {
        "show": "Latent Space",
        "episode": "What Are Agents? The Year of AI Agents",
        "episode_id": "2024",
        "guest": "swyx & Alessio Fanelli",
        "category": "AI Agents",
        "duration": "~1h 15min",
        "why": "The clearest explanation of what AI agents actually are, why they keep failing in practice, and what it would take for them to actually work reliably — from engineers who build with them every day.",
        "spotify_search": "Latent Space What Are Agents Year of AI Agents 2024",
    },
    {
        "show": "Freakonomics Radio",
        "episode": "Is the U.S. Education System Failing? (And What to Do About It)",
        "episode_id": "2022",
        "guest": "Stephen Dubner",
        "category": "Society & Economics",
        "duration": "~45min",
        "why": "Uses hard data to challenge what most people believe about education outcomes — and connects it to the AI skills gap everyone is now worried about. A good episode to understand where the next generation of AI workers will come from.",
        "spotify_search": "Freakonomics Radio US Education System Failing 2022",
    },
    {
        "show": "Freakonomics Radio",
        "episode": "Could the Next Einstein Be Hiding in Africa?",
        "episode_id": "2022",
        "guest": "Stephen Dubner",
        "category": "Global Economics",
        "duration": "~42min",
        "why": "Explores why so much global talent goes undiscovered and what AI-powered education could unlock — one of those episodes that makes you think totally differently about where human potential is being wasted.",
        "spotify_search": "Freakonomics Radio Einstein Africa talent 2022",
    },
    {
        "show": "The Knowledge Project (Farnam Street)",
        "episode": "Charlie Munger: The Psychology of Human Misjudgment",
        "episode_id": "#61",
        "guest": "Charlie Munger (via archival audio)",
        "category": "Mental Models & Decision Making",
        "duration": "~1h 10min",
        "why": "Munger's famous Harvard speech on the 25 cognitive biases that cause people to make terrible decisions — applied to investing, business, and everyday life. One of the most referenced talks in the history of business thinking.",
        "spotify_search": "Knowledge Project Charlie Munger Psychology Misjudgment",
    },
    {
        "show": "The Knowledge Project (Farnam Street)",
        "episode": "Daniel Kahneman: Noise, Bias, and Better Decisions",
        "episode_id": "#127",
        "guest": "Daniel Kahneman",
        "category": "Decision Making",
        "duration": "~1h 20min",
        "why": "The Nobel Prize-winning psychologist explains 'noise' — the random variation in human judgment that's just as damaging as bias, but almost never talked about. Directly applicable to any job involving decisions.",
        "spotify_search": "Knowledge Project Daniel Kahneman Noise Bias Decisions 127",
    },
    {
        "show": "a16z Podcast",
        "episode": "The New AI Stack: From Models to Applications",
        "episode_id": "2024",
        "guest": "Andreessen Horowitz partners",
        "category": "AI & Venture Capital",
        "duration": "~55min",
        "why": "a16z maps out the layers of the AI tech stack — from foundation models to APIs to apps — and explains where they think the real business value will end up. Useful mental model for anyone building or investing in AI.",
        "spotify_search": "a16z Podcast New AI Stack Models Applications 2024",
    },
    {
        "show": "a16z Podcast",
        "episode": "Software Is Still Eating the World — Now with AI",
        "episode_id": "2023",
        "guest": "Marc Andreessen",
        "category": "Tech & Business",
        "duration": "~50min",
        "why": "An update to Andreessen's famous 2011 essay — applied to the AI moment. He argues AI is not a bubble but a genuine platform shift, and explains which industries will be transformed first and why.",
        "spotify_search": "a16z Marc Andreessen Software Eating World AI 2023",
    },
    {
        "show": "Invest Like the Best",
        "episode": "Jensen Huang: The Geometry of the GPU Era",
        "episode_id": "2024",
        "guest": "Jensen Huang",
        "category": "Investing & AI",
        "duration": "~1h 15min",
        "why": "Jensen explains the economics of the AI compute buildout, why demand for GPUs shows no sign of slowing, and how NVIDIA thinks about the next decade of hardware. Essential context for understanding AI investment.",
        "spotify_search": "Invest Like the Best Jensen Huang GPU Era 2024",
    },
    {
        "show": "Invest Like the Best",
        "episode": "Patrick Collison: Building Stripe and the Science of Progress",
        "episode_id": "2022",
        "guest": "Patrick Collison",
        "category": "Investing & Business",
        "duration": "~1h 25min",
        "why": "Stripe's CEO talks about building payment infrastructure, why scientific progress has slowed down, and what he's doing about it with Stripe and his personal research into how great institutions are built.",
        "spotify_search": "Invest Like the Best Patrick Collison Stripe Science Progress",
    },
    {
        "show": "Eye on AI",
        "episode": "Stuart Russell on Why Current AI Is Not the Path to AGI",
        "episode_id": "2023",
        "guest": "Stuart Russell",
        "category": "AI Research",
        "duration": "~55min",
        "why": "The author of the world's most-used AI textbook explains why he thinks LLMs are impressive but fundamentally the wrong direction for building truly intelligent machines — and what the right approach might look like.",
        "spotify_search": "Eye on AI Stuart Russell AGI current AI path",
    },
    {
        "show": "Eye on AI",
        "episode": "Demis Hassabis on AlphaFold and the Future of Scientific Discovery",
        "episode_id": "2022",
        "guest": "Demis Hassabis",
        "category": "AI & Science",
        "duration": "~50min",
        "why": "DeepMind's CEO explains how AlphaFold solved one of biology's hardest problems (protein folding) and why he thinks AI is on the verge of accelerating science itself — not just making chatbots faster.",
        "spotify_search": "Eye on AI Demis Hassabis AlphaFold Scientific Discovery",
    },
    {
        "show": "The Daily (New York Times)",
        "episode": "The A.I. Wars",
        "episode_id": "Feb 2023",
        "guest": "NYT Tech Reporters",
        "category": "AI News",
        "duration": "~32min",
        "why": "Recorded during the early ChatGPT frenzy — NYT reporters explain what Google's AI 'red code' moment actually was, why Microsoft's Bing AI went off the rails, and what the AI search wars mean for everyone.",
        "spotify_search": "The Daily New York Times AI Wars February 2023",
    },
    {
        "show": "The Daily (New York Times)",
        "episode": "How AI Could Upend the World Even More Than the Internet",
        "episode_id": "2023",
        "guest": "Cade Metz",
        "category": "AI & Society",
        "duration": "~35min",
        "why": "NYT's AI reporter has covered this field for a decade. He explains what's genuinely new about this wave of AI, what the hype gets wrong, and what long-time researchers are actually worried about.",
        "spotify_search": "The Daily NYT How AI Upend World More Than Internet",
    },
    {
        "show": "Darknet Diaries",
        "episode": "The LinkedIn Hack",
        "episode_id": "#86",
        "guest": "Jack Rhysider",
        "category": "Cybersecurity",
        "duration": "~52min",
        "why": "The inside story of how 700 million LinkedIn records were scraped and sold — told as a thriller. Directly relevant as AI companies now scrape the internet at massive scale and the legal battles are just beginning.",
        "spotify_search": "Darknet Diaries LinkedIn Hack 86",
    },
    {
        "show": "Darknet Diaries",
        "episode": "The Lazarus Heist",
        "episode_id": "#123",
        "guest": "Jack Rhysider",
        "category": "Cybersecurity",
        "duration": "~1h 5min",
        "why": "North Korea's elite hacking unit stole $80 million from Bangladesh's central bank using a series of perfectly timed cyber moves. One of the most audacious cyberheists in history, told like a movie.",
        "spotify_search": "Darknet Diaries Lazarus Heist 123",
    },
    {
        "show": "Lex Fridman Podcast",
        "episode": "Demis Hassabis: DeepMind, AlphaFold, Gemini, and Nobel Prize",
        "episode_id": "#431",
        "guest": "Demis Hassabis",
        "category": "AI",
        "duration": "~3h 15min",
        "why": "Recorded after Hassabis won the Nobel Prize for AlphaFold. He talks about building DeepMind from a small London office, how they solved protein folding, and why he thinks AI will solve every major scientific problem in our lifetime.",
        "spotify_search": "Lex Fridman Demis Hassabis DeepMind AlphaFold Nobel 431",
    },
    {
        "show": "Lex Fridman Podcast",
        "episode": "Pieter Levels: Building Solo Startups with AI",
        "episode_id": "#440",
        "guest": "Pieter Levels",
        "category": "AI & Indie Building",
        "duration": "~2h 50min",
        "why": "The creator of Nomad List and RemoteOK explains how a single person with the right AI tools can now build products that used to require entire engineering teams — and how he makes millions from his solo projects.",
        "spotify_search": "Lex Fridman Pieter Levels Solo Startups AI 440",
    },
    {
        "show": "Huberman Lab",
        "episode": "How to Enhance Performance and Learning Using Dopamine",
        "episode_id": "Episode 42",
        "guest": "Andrew Huberman",
        "category": "Neuroscience & Productivity",
        "duration": "~2h 35min",
        "why": "Huberman explains the neuroscience of motivation peaks and crashes — including why too many rewards can actually kill your drive, and how to structure your work to stay in a consistent high-performance state.",
        "spotify_search": "Huberman Lab Enhance Performance Learning Dopamine Episode 42",
    },
    {
        "show": "Masters of Scale",
        "episode": "Satya Nadella: Microsoft's AI Reinvention",
        "episode_id": "2023",
        "guest": "Satya Nadella",
        "category": "AI & Business Leadership",
        "duration": "~42min",
        "why": "Nadella explains the cultural transformation that allowed Microsoft to move faster than Google on AI despite Google's head start — and how he convinced an entire 200,000-person company to embrace OpenAI overnight.",
        "spotify_search": "Masters of Scale Satya Nadella Microsoft AI Reinvention",
    },
    {
        "show": "All-In Podcast",
        "episode": "Balaji Srinivasan: AI, Bitcoin, and the Network State",
        "episode_id": "E118",
        "guest": "Balaji Srinivasan",
        "category": "AI & Technology Future",
        "duration": "~1h 45min",
        "why": "One of tech's most contrarian thinkers lays out his vision for how AI and crypto together will restructure governments, companies, and nations. Provocative — you'll disagree with some of it and be surprised by the rest.",
        "spotify_search": "All-In Balaji Srinivasan AI Bitcoin Network State E118",
    },
    {
        "show": "No Priors",
        "episode": "The State of AI Coding: GitHub Copilot, Cursor, and What's Next",
        "episode_id": "2024",
        "guest": "AI coding researchers",
        "category": "AI & Software Development",
        "duration": "~55min",
        "why": "A detailed look at where AI coding assistants are now, where they're failing, and what the next breakthrough will look like — from people building these tools. Very relevant to anyone using Claude Code or Cursor.",
        "spotify_search": "No Priors AI Coding Copilot Cursor 2024",
    },
    {
        "show": "Freakonomics Radio",
        "episode": "Why Is There So Much Fraud in Academia? (And What to Do About It)",
        "episode_id": "2023",
        "guest": "Stephen Dubner",
        "category": "Science & Society",
        "duration": "~48min",
        "why": "A surprisingly relevant episode as AI-generated academic content floods research — Dubner examines what causes smart people to fake results and how institutions are (and aren't) catching them.",
        "spotify_search": "Freakonomics Radio Fraud Academia 2023",
    },
    {
        "show": "Invest Like the Best",
        "episode": "Sam Altman: Building the Future with OpenAI",
        "episode_id": "2024",
        "guest": "Sam Altman",
        "category": "AI & Investing",
        "duration": "~1h 10min",
        "why": "Altman talks candidly about OpenAI's business model, why they chose a for-profit structure, the economics of training frontier models, and what it actually costs to stay at the frontier — numbers most people don't know.",
        "spotify_search": "Invest Like the Best Sam Altman Building Future OpenAI 2024",
    },
    {
        "show": "The Tim Ferriss Show",
        "episode": "Reid Hoffman: Navigating AI, Work, and Life in the Machine Age",
        "episode_id": "#722",
        "guest": "Reid Hoffman",
        "category": "AI & Career",
        "duration": "~2h 10min",
        "why": "LinkedIn's founder and early AI investor explains how he thinks every professional should be adapting to AI right now — with specific, practical advice about which skills to build and which to stop worrying about.",
        "spotify_search": "Tim Ferriss Reid Hoffman AI Work Life Machine Age 722",
    },
]


def pick_episode_of_the_day() -> dict:
    """Returns one episode deterministically based on today's date — same pick all day."""
    day_index = date.today().timetuple().tm_yday  # 1–365
    return EPISODES[day_index % len(EPISODES)]
